INSERT INTO equipos
(nombre, pais, estrellas, escudo)
VALUES
("Kaa Gent", "Bélgica", 2,"static/Img/escudos/KaaGent.svg"),
("Sparta Praha","República Checha", 3, "static/Img/escudos/SpartaPraha.svg"),
("Bayern Múnich","Alemania", 5, "static/Img/escudos/BayernMunchen.svg"),
("Borussia Monchengladbach","Alemania", 4, "static/Img/escudos/BorussiaMonchengladbach.svg"),
("Wolfsburgo","Alemania", 4, "static/Img/escudos/Wolfsburgo.svg"),
("Olympiacos","Grecia", 3.5, "static/Img/escudos/Olympiacos.svg"),
("Zenit","Rusia", 4, "static/Img/escudos/Zenit.svg"),
("Basel 1893","Suiza", 3.5, "static/Img/escudos/Basel.svg"),
("Dinamo de Kiev","Ucrania", 3.5, "static/Img/escudos/DynamoKyiv.svg"),
("Olympique de Marseille","Francia", 4, "static/Img/escudos/OlympiqueMarseille.svg"),
("Atletico de Madrid","España", 4.5, "static/Img/escudos/AtleticoMadrid.svg"),
("FC Barcelona","España", 5, "static/Img/escudos/Barcelona.svg"),
("Real Madrid","España", 5, "static/Img/escudos/RealMadrid.svg"),
("Sevilla FC","España", 4, "static/Img/escudos/Sevilla.svg"),
("Valencia CF","España", 4, "static/Img/escudos/Valencia.svg"),
("Olympique Lyonnais","Francia", 4, "static/Img/escudos/OlympiqueLyonnais.svg"),
("Paris saint-germain","Francia", 5, "static/Img/escudos/ParisSaint-Germain.svg"),
("PSV","Holanda", 4, "static/Img/escudos/PSV.svg"),
("Arsenal (North London)","Inglaterra", 4.5, "static/Img/escudos/Arsenal.svg"),
("Chelsea (London FC)","Inglaterra", 5, "static/Img/escudos/Chelsea.svg"),
("Manchester city (Man. Blue)","Inglaterra", 4.5, "static/Img/escudos/ManchesterCity.svg"),
("ACF Fiorentina","Italia", 4.5, "static/Img/escudos/Fiorentina.svg"),
("Juventus FC","Italia", 4.5, "static/Img/escudos/Juventus.svg"),
("Manchester United","Inglaterra", 4.5, "static/Img/escudos/ManUnited.svg"),
("A.S. Roma","Italia", 4.5, "static/Img/escudos/Roma.svg"),
("Empoli FC","Italia", 3.5, "static/Img/escudos/Empoli.svg"),
("SL Benfica","Portugal", 4, "static/Img/escudos/Benfica.svg"),
("FC Porto","Portugal", 4, "static/Img/escudos/Porto.svg"),
("Feyenoord","Holanda", 3.5, "static/Img/escudos/Feyenoord.svg"),
("AS Monaco FC","Francia", 4, "static/Img/escudos/Monaco.svg"),
("Ajax","Holanda", 4, "static/Img/escudos/Ajax.svg"),
("Tottenham (North East London)","Inglaterra", 4.5, "static/Img/escudos/Tottenham.svg"),
("Atalanta B.C.","Italia", 3.5, "static/Img/escudos/Atalanta.svg"),
("Internazionale Milano","Italia", 4.5, "static/Img/escudos/InternazionaleMilano.svg"),
("S.S. Lazio","Italia", 4.5, "static/Img/escudos/Lazio.svg"),
("A.C. Milan","Italia", 4, "static/Img/escudos/Milan.svg"),
("Bologna F.C.","Italia", 2.5, "static/Img/escudos/Bologna.svg"),
("Real Sporting","España", 2, "static/Img/escudos/RealSporting.svg"),
("Granada C.F","España", 3, "static/Img/escudos/Granada.svg"),
("Sporting","Portugal", 4, "static/Img/escudos/Sporting.svg"),
("M.A Yellow Blue","Portugal", 1.5, "static/Img/escudos/YellowBlue.png");