# Generated by Django 4.0 on 2023-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('estrellas', models.IntegerField(null=True, verbose_name='Numero de estrellas')),
                ('copas', models.IntegerField(null=True, verbose_name='Numero de copas')),
                ('foto', models.ImageField(null=True, upload_to='img/jugadores', verbose_name='Foto del jugador')),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(null=True, upload_to='img/escudos', verbose_name='Imagen del escudo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='pais',
            field=models.CharField(max_length=25, null=True, verbose_name='Pais'),
        ),
    ]
