# Generated by Django 4.0 on 2023-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_jugador_alter_equipo_escudo_alter_equipo_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='copas',
        ),
        migrations.AddField(
            model_name='jugador',
            name='copasAmerica',
            field=models.IntegerField(null=True, verbose_name='Numero de copas America'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='copasEuro',
            field=models.IntegerField(null=True, verbose_name='Numero de copas de Europa'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='copasMundial',
            field=models.IntegerField(null=True, verbose_name='Numero de copas mundiales'),
        ),
    ]
