# Generated by Django 5.0 on 2023-12-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("torneo", "0006_jugador_carta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partido",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "golesLocal",
                    models.IntegerField(
                        null=True, verbose_name="Numero de goles del equipo local"
                    ),
                ),
                (
                    "golesVisitante",
                    models.IntegerField(
                        null=True, verbose_name="Numero de goles del equipo local"
                    ),
                ),
                (
                    "equipoLocal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipoLocal",
                        to="torneo.equipo",
                    ),
                ),
                (
                    "equipoVisitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipoVisitante",
                        to="torneo.equipo",
                    ),
                ),
                (
                    "ganador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="torneo.jugador"
                    ),
                ),
                (
                    "jugadorLocal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugadorLocal",
                        to="torneo.jugador",
                    ),
                ),
                (
                    "jugadorVisitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugadorVisitante",
                        to="torneo.jugador",
                    ),
                ),
            ],
            options={
                "db_table": "partidos",
            },
        ),
    ]
