# Generated by Django 5.0 on 2023-12-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("torneo", "0007_partido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="ganador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ganador",
                to="torneo.jugador",
            ),
        ),
    ]
